# Generated by Django 3.1.2 on 2020-10-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_sms_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_sender_id', models.IntegerField(blank=True, null=True)),
                ('wallet_reciever_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('movement_type', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('commission', models.CharField(max_length=255)),
                ('time', models.IntegerField(default=1604146432.1913164)),
                ('secret_t', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
                ('card', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(default=0, max_length=255)),
                ('status', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=192, null=True)),
                ('secret_id', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='sms_approve',
            name='time',
            field=models.IntegerField(default=1604146432.1913164),
        ),
    ]
